[package]
name = "solana-version"
version = "0.4.4"
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.11"
serde = "1.0.122"
serde_derive = "1.0.103"
solana-frozen-abi = { path = "../frozen-abi", version = "=1.6.14" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.6.14" }
solana-logger = { path = "../logger", version = "=1.6.14" }
solana-sdk = { path = "../sdk", version = "=1.6.14" }

[lib]
name = "solana_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.2"
