[package]
name = "solana-version"
version = "0.7.0"
license = "Apache-2.0"
edition = "2021"

[dependencies]
log = "0.4.14"
semver = "1.0.6"
serde = "1.0.136"
serde_derive = "1.0.103"
solana-frozen-abi = { path = "../frozen-abi", version = "=1.13.7" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "=1.13.7" }
solana-sdk = { path = "../sdk", version = "=1.13.7" }

[lib]
name = "solana_version"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = "0.4"
