[workspace]
members = [
    "account-decoder",
    "accounts-bench",
    "accounts-cluster-bench",
    "banking-bench",
    "banks-client",
    "banks-interface",
    "banks-server",
    "bench-streamer",
    "bench-tps",
    "bench-tps-evm",
    "bucket_map",
    "bloom",
    "clap-utils",
    "cli-config",
    "cli-output",
    "client",
    "core",
    "dos",
    "download-utils",
    "entry",
    "faucet",
    "frozen-abi",
    "perf",
    "validator",
    "genesis",
    "genesis-utils",
    "geyser-plugin-interface",
    "geyser-plugin-manager",
    "gossip",
    "install",
    "keygen",
    "ledger",
    "ledger-tool",
    "local-cluster",
    "logger",
    "log-analyzer",
    "merkle-root-bench",
    "merkle-tree",
    "storage-bigtable",
    "storage-proto",
    "streamer",
    "measure",
    "metrics",
    "net-shaper",
    "notifier",
    "evm-utils/evm-bridge",
    "evm-utils/programs/evm_loader",
    "evm-utils/evm-state",
    "evm-utils/evm-rpc",
    "poh",
    "poh-bench",
    "program-test",
    "programs/address-lookup-table",
    "programs/address-lookup-table-tests",
    "programs/ed25519-tests",
    "programs/bpf_loader",
    "programs/bpf_loader/gen-syscall-list",
    "programs/compute-budget",
    "programs/config",
    "programs/sleep",
    "programs/stake",
    "programs/vote",
    "remote-wallet",
    "rpc",
    "runtime",
    "runtime/store-tool",
    "sdk",
    "sdk/cargo-build-bpf",
    "sdk/cargo-test-bpf",
    "send-transaction-service",
    "stake-accounts",
    "sys-tuner",
    "tokens",
    "transaction-dos",
    "transaction-status",
    "upload-perf",
    "net-utils",
    "version",
    "cli",
    "rayon-threadlimit",
    "watchtower",
    "replica-node",
    "replica-lib",
    "test-validator",
    "rpc-test",
    "client-test",
]

exclude = [
    "programs/bpf",
]

# TODO: Remove once the "simd-accel" feature from the reed-solomon-erasure
# dependency is supported on Apple M1. v2 of the feature resolver is needed to
# specify arch-specific features.
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.crates-io]
primitive-types = { git = "https://github.com/velas/parity-common", branch = "borsh-9-support" }

[patch."https://github.com/velas/evm"]
evm = { git = "ssh://git@github.com/velas/evm-security-fixes.git", branch = "add-traces" }
