[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-genesis"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.14"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-genesis"

[dependencies]
base64 = "0.12.3"
clap = "2.33.1"
chrono = "0.4"
serde = "1.0.122"
serde_json = "1.0.56"
serde_yaml = "0.8.13"
solana-budget-program = { path = "../programs/budget", version = "=1.6.14" }
solana-clap-utils = { path = "../clap-utils", version = "=1.6.14" }
solana-cli-config = { path = "../cli-config", version = "=1.6.14" }
solana-exchange-program = { path = "../programs/exchange", version = "=1.6.14" }
solana-ledger = { path = "../ledger", version = "=1.6.14" }
solana-logger = { path = "../logger", version = "=1.6.14" }
solana-runtime = { path = "../runtime", version = "=1.6.14" }
solana-sdk = { path = "../sdk", version = "=1.6.14" }
solana-stake-program = { path = "../programs/stake", version = "=1.6.14" }
solana-version = { path = "../version", version = "=0.4.4" }
solana-vest-program = { path = "../programs/vest", version = "=1.6.14" }
solana-vote-program = { path = "../programs/vote", version = "=1.6.14" }

solana-evm-loader-program = { path = "../evm-utils/programs/evm_loader" }
evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }

tempfile = "3.1.0"
once_cell = "1.7.2"
log = "0.4"

[[bin]]
name = "velas-genesis"
path = "src/main.rs"

[lib]
name = "solana_genesis"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["with_evm"]
with_evm = []
