[package]
name = "solana-evm-loader-program"
version = "0.1.0"
description = "Solana EVM loader"
authors = ["Vladimir Motylenko <vld@stegos.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
log = "0.4.8"
solana-logger = { path = "../../../logger", version = "1.3.11" }
solana-sdk = { path = "../../../sdk", version = "1.3.11" }
evm-state = { path = "../../evm-state", version = "0.1" }
assert_matches = "1.4"
bincode = "1.3.1"
serde = "1.0"
primitive-types = "0.8.0"
hex = "0.4.2"
simple_logger = "1.11.0"
sha3 = "0.9.1"

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_evm_loader_program"
