[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-ledger-tool"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.14"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-ledger-tool"

[dependencies]
bs58 = "0.3.1"
bytecount = "0.6.0"
clap = "2.33.1"
csv = "1.1.3"
futures = "0.3.8"
futures-util = "0.3.5"
histogram = "*"
itertools = "0.9.0"
log = { version = "0.4.11" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.56"
serde_yaml = "0.8.13"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.14" }
solana-cli-output = { path = "../cli-output", version = "=1.6.14" }
solana-ledger = { path = "../ledger", version = "=1.6.14" }
solana-logger = { path = "../logger", version = "=1.6.14" }
solana-measure = { path = "../measure", version = "=1.6.14" }
solana-runtime = { path = "../runtime", version = "=1.6.14" }
solana-sdk = { path = "../sdk", version = "=1.6.14" }
solana-stake-program = { path = "../programs/stake", version = "=1.6.14" }
solana-storage-bigtable = { path = "../storage-bigtable", version = "=1.6.14" }
solana-transaction-status = { path = "../transaction-status", version = "=1.6.14" }
solana-version = { path = "../version", version = "=0.5.0" }
solana-vote-program = { path = "../programs/vote", version = "=1.6.14" }

tempfile = "3.1.0"
tokio = { version = "1", features = ["full"] }

evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
triedb = { git = "https://github.com/velas/triedb", branch = "feat/gc-simple", features = ["rocksdb"] }
rlp = "0.5.0"
anyhow = "1.0.43"
rayon = "1.5.0"

[dev-dependencies]
assert_cmd = "1.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[target."cfg(unix)".dependencies]
signal-hook = "0.1.15"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
