[package]
name = "evm-bridge"
version = "0.1.0"
authors = ["Vladimir Motylenko <vld@stegos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evm-rpc = { path = "../evm-rpc" }
solana-sdk = { path = "../../sdk", version = "1.4.0" }
solana-client = { path = "../../client", version = "1.4.0" }
solana-cli-config = { path = "../../cli-config", version = "1.4.0" }
solana-core = { path = "../../core", version = "1.4.0" }
solana-runtime = { path = "../../runtime", version = "1.4.0" }
solana-transaction-status = { path = "../../transaction-status", version = "1.4.0" }
solana-account-decoder = { path = "../../account-decoder", version = "1.4.0" }
solana-evm-loader-program = { path = "../programs/evm_loader" }
structopt = { version = "0.3", features = [ "paw" ] }
serde_json="1.0.60"
env_logger = "0.8.2"
paw = "1.0"
rlp = "0.4.5"
sha3="0.9.1"
primitive-types = "0.7"
secp256k1 = { version = "0.19.0", features = ["recovery", "global-context"] }
evm-state = { path = "../evm-state" }
log = "0.4.11"
jsonrpc-core = "14.2.0"
jsonrpc-core-client = { version = "14.2.0", features = ["ws"] }
jsonrpc-derive = "14.2.1"
jsonrpc-http-server = "14.2.0"
jsonrpc-pubsub = "14.2.0"
jsonrpc-ws-server = "14.2.0"
num_cpus = "1.13.0"
