[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-dos"
version = "1.6.14"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
bincode = "1.3.1"
clap = "2.33.1"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.0"
solana-clap-utils = { path = "../clap-utils", version = "=1.6.14" }
solana-core = { path = "../core", version = "=1.6.14" }
solana-ledger = { path = "../ledger", version = "=1.6.14" }
solana-logger = { path = "../logger", version = "=1.6.14" }
solana-net-utils = { path = "../net-utils", version = "=1.6.14" }
solana-runtime = { path = "../runtime", version = "=1.6.14" }
solana-sdk = { path = "../sdk", version = "=1.6.14" }
solana-version = { path = "../version", version = "=0.4.4" }
solana-client = { path = "../client", version = "=1.6.14" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
