name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - devnet
      - 'build/**'

jobs:
  docker-build-push:
    name: Build and push
    runs-on: build-dedicated
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_HOST }}
      - name: Build, tag, and push image 
        id: build
        env:
          REGISTRY: ${{ secrets.REGISTRY_HOST }}/velas
          REPOSITORY: velas-solana
          IMAGE_TAG: ${{github.sha}}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --no-cache  .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "::set-output name=repository::$REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"

