[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-bench-tps"
version = "1.10.41"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.1"
crossbeam-channel = "0.5"
log = "0.4.14"
rayon = "1.5.1"
serde_json = "1.0.79"
serde_yaml = "0.8.23"
solana-clap-utils = { path = "../clap-utils", version = "=1.10.41" }
solana-cli-config = { path = "../cli-config", version = "=1.10.41" }
solana-client = { path = "../client", version = "=1.10.41" }
solana-core = { path = "../core", version = "=1.10.41" }
solana-faucet = { path = "../faucet", version = "=1.10.41" }
solana-genesis = { path = "../genesis", version = "=1.10.41" }
solana-gossip = { path = "../gossip", version = "=1.10.41" }
solana-logger = { path = "../logger", version = "=1.10.41" }
solana-measure = { path = "../measure", version = "=1.10.41" }
solana-metrics = { path = "../metrics", version = "=1.10.41" }
solana-net-utils = { path = "../net-utils", version = "=1.10.41" }
solana-rpc = { path = "../rpc", version = "=1.10.41" }
solana-runtime = { path = "../runtime", version = "=1.10.41" }
solana-sdk = { path = "../sdk", version = "=1.10.41" }
solana-streamer = { path = "../streamer", version = "=1.10.41" }
solana-version = { path = "../version", version = "=0.7.0" }
thiserror = "1.0"

[dev-dependencies]
serial_test = "0.6.0"
solana-local-cluster = { path = "../local-cluster", version = "=1.10.41" }
solana-test-validator = { path = "../test-validator", version = "=1.10.41" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
